# Issue 0012 (library-manager) — "New library" must work when the writable
# library.defs is only DISCOVERABLE on the search path, not listed in
# $XSCHEM_LIBRARY_DEFS (which is unset by default).
#
# Fixture mimics the OA layout: a parent dir holds library.defs, the per-library
# subdirs are on the search list `pathlist`, and XSCHEM_LIBRARY_DEFS is UNSET.
# Backend procs under test live in src/library_defs.tcl.
#
# Headless (no X needed). Run with --pipe from src/:
#   ./xschem --pipe -q --script ../tests/headless/test_lib_new_discovered_defs.tcl

set fail 0
proc check {name ok detail} {
  global fail
  if {$ok} { puts "ok:   $name $detail" } else { puts "FAIL: $name $detail"; incr fail }
}
proc errs {body} { return [catch [list uplevel 1 $body]] }
# is {name path} present in `xschem libraries`?
proc lib_listed {name} {
  if {[catch {xschem libraries} r]} { return 0 }
  foreach pair $r { if {[lindex $pair 0] eq $name} { return 1 } }
  return 0
}
proc defs_has_define {defs name} {
  if {[catch {open $defs r} fp]} { return 0 }
  set txt [read $fp]; close $fp
  foreach line [split $txt \n] {
    if {[regexp {^\s*DEFINE\s+(\S+)\s} [string trim $line] -> n] && $n eq $name} { return 1 }
  }
  return 0
}

# --- fixture: an "OA" tree. library.defs lives in the parent; the library
#     subdirs (devices, examples) are what sits on the search path. ----------
set tmp [file join [pwd] _lib0012_[pid]]
file delete -force $tmp
set oa $tmp/oa
file mkdir $oa/devices $oa/examples

set defs [file join $oa library.defs]
set fp [open $defs w]
puts $fp "# generated by xschem_libmigrate"
puts $fp "DEFINE devices devices"
puts $fp "DEFINE examples examples"
close $fp

# Critical: XSCHEM_LIBRARY_DEFS is UNSET (the default). The library.defs is only
# reachable because its subdirs are on the search list.
catch {unset ::XSCHEM_LIBRARY_DEFS}
catch {unset ::env(XSCHEM_LIBRARY_DEFS)}
set ::pathlist [list $oa/devices $oa/examples]

# Isolate the personal registry to a temp dir for the WHOLE run, so the real
# $USER_CONF_DIR/library.defs (~/.xschem/library.defs) is never read or written
# — otherwise a stray DEFINE there (e.g. a hand-created SANDBOX) would leak into
# these cases. LND8 repoints it to exercise the personal-fallback explicitly.
set saved_conf [expr {[info exists ::USER_CONF_DIR] ? $::USER_CONF_DIR : {}}]
file mkdir $tmp/conf0
set ::USER_CONF_DIR $tmp/conf0

# === LND1 — the discoverable library.defs is found as the primary write target
check "LND1 primary_defs_file finds the discoverable library.defs" \
  [expr {[file normalize [library_primary_defs_file]] eq [file normalize $defs]}] \
  "(=> '[library_primary_defs_file]')"

# === LND2 — its existing DEFINEs resolve through the registry (read side knows it)
check "LND2a discovered defs: devices resolves" \
  [expr {[file normalize [xschem library devices]] eq [file normalize $oa/devices]}] \
  "(=> [xschem library devices])"
check "LND2b discovered defs: examples resolves" \
  [expr {[file normalize [xschem library examples]] eq [file normalize $oa/examples]}] \
  "(=> [xschem library examples])"

# === LND3 — library_new with a BLANK dir succeeds (the reported failure) ------
check "LND3a new library SANDBOX (blank dir) does not error" \
  [expr {![errs {library_new SANDBOX {}}]}] {}
check "LND3b SANDBOX dir created beside library.defs" \
  [file isdirectory [file join $oa SANDBOX]] "(=> $oa/SANDBOX)"
check "LND3c DEFINE SANDBOX appended to the discovered library.defs" \
  [defs_has_define $defs SANDBOX] {}

# === LND4 — the new library is immediately visible to the registry -----------
check "LND4a SANDBOX resolves via xschem library" \
  [expr {[file normalize [xschem library SANDBOX]] eq [file normalize $oa/SANDBOX]}] \
  "(=> [xschem library SANDBOX])"
check "LND4b SANDBOX listed in xschem libraries" [lib_listed SANDBOX] {}

# === LND5 — unregister scans discovered defs too (symmetry) ------------------
check "LND5a unregister SANDBOX does not error" \
  [expr {![errs {library_unregister SANDBOX}]}] {}
check "LND5b DEFINE SANDBOX removed from the discovered library.defs" \
  [expr {![defs_has_define $defs SANDBOX]}] {}

# === LND6 — also works when library.defs sits IN a pathlist dir (not parent) --
set flat $tmp/flat
file mkdir $flat
set fdefs [file join $flat library.defs]
set fp [open $fdefs w]; puts $fp "# flat-style"; close $fp
set ::pathlist [list $flat]
check "LND6 primary_defs_file finds a library.defs in the pathlist dir itself" \
  [expr {[file normalize [library_primary_defs_file]] eq [file normalize $fdefs]}] \
  "(=> '[library_primary_defs_file]')"

# === LND7 — explicit XSCHEM_LIBRARY_DEFS still wins over a discovered one -----
# An explicit defs defines 'devices' -> a DIFFERENT path; it must take precedence
# over the discovered OA defs (which maps devices -> $oa/devices).
set xdir $tmp/explicit
file mkdir $xdir/mydevices
set xdefs [file join $xdir library.defs]
set fp [open $xdefs w]; puts $fp "DEFINE devices $xdir/mydevices"; close $fp
set ::XSCHEM_LIBRARY_DEFS $xdefs
set ::pathlist [list $oa/devices $oa/examples]
check "LND7 explicit DEFINE beats a discovered defs of the same name" \
  [expr {[file normalize [xschem library devices]] eq [file normalize $xdir/mydevices]}] \
  "(=> [xschem library devices])"

# === LND8 — NOTHING on the path: fall back to the personal library.defs ------
# Reproduces the stock-session failure: no $XSCHEM_LIBRARY_DEFS, and no
# library.defs anywhere on the search path. Creating a library must still work by
# establishing a personal registry in $USER_CONF_DIR (the absent file is created).
set conf $tmp/conf
file mkdir $conf
set pdefs [file join $conf library.defs]
catch {unset ::XSCHEM_LIBRARY_DEFS}
catch {unset ::env(XSCHEM_LIBRARY_DEFS)}
set ::pathlist [list $tmp/nodefs_a $tmp/nodefs_b]   ;# dirs with no library.defs
file mkdir $tmp/nodefs_a $tmp/nodefs_b
set ::USER_CONF_DIR $conf
check "LND8a primary_defs_file falls back to the personal library.defs" \
  [expr {[file normalize [library_primary_defs_file]] eq [file normalize $pdefs]}] \
  "(=> '[library_primary_defs_file]')"
check "LND8b new library PERSONALLIB (blank dir) does not error" \
  [expr {![errs {library_new PERSONALLIB {}}]}] {}
check "LND8c personal library.defs created" [file isfile $pdefs] "(=> $pdefs)"
check "LND8d DEFINE PERSONALLIB appended to personal defs" [defs_has_define $pdefs PERSONALLIB] {}
check "LND8e PERSONALLIB resolves via the registry" \
  [expr {[file normalize [xschem library PERSONALLIB]] eq [file normalize $conf/PERSONALLIB]}] \
  "(=> [xschem library PERSONALLIB])"

# --- cleanup ---------------------------------------------------------------
if {$saved_conf ne {}} { set ::USER_CONF_DIR $saved_conf } else { catch {unset ::USER_CONF_DIR} }
catch {unset ::XSCHEM_LIBRARY_DEFS}
file delete -force $tmp

if {$fail} { puts "RESULT: $fail FAILED" } else { puts "RESULT: all passed" }
