# gen_actions.tcl — regenerate the palette-only action rows in src/actions.csv
# from the menu inventory (menu_items.csv in this directory).
#
# Emits CSV rows (id,type,menu,label,accel,command,submenu,hook,help) for every
# CLEAN command — single-line, no inline {} script, no embedded quoting/subst
# ([ ] " \ $) — outside the File menu (which is hand-curated in actions.csv).
# The gnarly inline-script / checkbutton / radiobutton items are deferred to a
# later phase (they need named-proc extraction first).
#
# Usage (writes the generated block to stdout):
#   tclsh code_analysis/menu_inventory/gen_actions.tcl >> src/actions.csv
#
# It is idempotent w.r.t. ids: existing ids in src/actions.csv are read first so
# generated ids never collide.

set here [file dirname [file normalize [info script]]]
set repo [file normalize $here/../..]
set srcdir $repo/src

source $srcdir/action_registry.tcl   ;# reuse action_parse_csv_line

proc csvq {s} {
  if {[regexp "\[\",\n\]" $s] || [string match { *} $s] || [string match {* } $s]} {
    return "\"[string map {\" \"\"} $s]\""
  }
  return $s
}

# ids already used in the CURATED part of actions.csv, to avoid collisions.
# Stop at the auto-generated import marker so this stays idempotent when the
# generated block is already present (re-running reproduces identical ids).
set seen {}
set af [open $srcdir/actions.csv r]
foreach line [split [read $af] "\n"] {
  if {[string match {# --- imported from menu inventory*} $line]} break
  if {$line eq {} || [string index $line 0] eq "#"} continue
  set f [action_parse_csv_line $line]
  if {[lindex $f 0] eq "id"} continue
  dict set seen [lindex $f 0] 1
}
close $af

set in [open $here/menu_items.csv r]
set data [read $in]; close $in
set header {}
set rows {}
foreach line [split $data "\n"] {
  if {$line eq {}} continue
  set f [action_parse_csv_line $line]
  if {$header eq {}} { set header $f; continue }
  # inventory columns: menu,type,label,accel,var,command,line
  lassign $f menu type label accel var command
  if {$type ne {command}} continue
  # Only high-confidence simple commands: no inline script / quoting / subst.
  if {$command eq {}} continue
  if {[regexp {[\{\}\[\]"\\$]} $command]} continue
  if {$label eq {} || $label eq {-}} continue
  if {$menu eq {file} || [string match {file.*} $menu]} continue
  set m $menu
  if {$m eq {(top)}} { set m toolbar }
  set slug [string tolower $label]
  regsub -all {[^a-z0-9]+} $slug _ slug
  set slug [string trim $slug _]
  set id "$m.$slug"
  set base $id; set k 2
  while {[dict exists $seen $id]} { set id "${base}_$k"; incr k }
  dict set seen $id 1
  set fields {}
  foreach v [list $id command $m $label $accel $command {} {} $label] {
    lappend fields [csvq $v]
  }
  lappend rows [join $fields ,]
}
puts "# --- imported from menu inventory: palette-only command rows -------------"
puts "# Auto-generated by code_analysis/menu_inventory/gen_actions.tcl. These keep"
puts "# their original menu name but are not yet generated (only File is); they are"
puts "# discoverable in the command palette. help defaults to the label for now."
foreach r $rows { puts $r }
puts stderr "generated [llength $rows] palette rows"
